# Generated by Django 4.0.7 on 2022-10-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access_token',
            new_name='refresh_token',
        ),
    ]
