# Generated by Django 4.0.7 on 2022-10-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_access_token_user_refresh_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
